import fs from "fs"
import path from "path"
import camelCase from 'camelcase';

const input = process.argv[2] || '.'

const prefix = ""

console.log('convert', input)

const stat = fs.statSync(input)
if (stat.isFile()) {
    convert(input)
} else {
    let files = fs.readdirSync(input)
    files.forEach(file => {
        const filename = path.join(input, file)
        const stat = fs.statSync(filename)
        const ext = path.extname(file)
        if (stat.isFile() && ext === ".svg") {
            convert(filename)
        }
    })
}

function convert(filename) {
    const ext = path.extname(filename)
    const base = path.basename(filename, ext)
    const out = filename + '.ts'

    fs.writeFileSync(out, "// !!! Generated by svg2ts.mjs\n")
    fs.appendFileSync(out, `// From ${filename} \n`)

    let variable = prefix + base + "_svg"
    variable = camelCase(variable, {pascalCase: true})

    fs.appendFileSync(out, `export const  ${variable} = \``)

    const content = fs.readFileSync(filename)

    fs.appendFileSync(out, content)
    fs.appendFileSync(out, "`\n")
}
