//!!! Generated by svg2meta.mjs
// From src\hmi\industry\device5.svg 
export const  Device5Meta = {
	"root": {
		"t": "1685081149005",
		"class": "icon",
		"viewBox": "0 0 1024 1024",
		"version": "1.1",
		"xmlns": "http://www.w3.org/2000/svg",
		"p-id": "69165",
		"xmlns:xlink": "http://www.w3.org/1999/xlink",
		"width": "200",
		"height": "200"
	},
	"markup": [
		{
			"tagName": "path",
			"selector": "path0"
		},
		{
			"tagName": "path",
			"selector": "path1"
		}
	],
	"attrs": {
		"path0": {
			"refD": "M849.6 1020H174.4c-8.8 0-16-7.2-16-16V20c0-8.8 7.2-16 16-16h675.2c8.8 0 16 7.2 16 16v984c0 8.8-7.2 16-16 16z m-659.2-32h643.2V36H190.4v952z",
			"refFill": "#303C42"
		},
		"path1": {
			"refD": "M768 795.2H256c-4.8 0-8-3.2-8-8V101.6c0-4.8 3.2-8 8-8h512c4.8 0 8 3.2 8 8v685.6c0 4-4 8-8 8z m-504-16h496V109.6H264v669.6zM512 960c-30.4 0-55.2-24.8-55.2-55.2 0-30.4 24.8-55.2 55.2-55.2 30.4 0 55.2 24.8 55.2 55.2 0 30.4-24.8 55.2-55.2 55.2z m0-94.4c-21.6 0-39.2 17.6-39.2 39.2s17.6 39.2 39.2 39.2 39.2-17.6 39.2-39.2-17.6-39.2-39.2-39.2z",
			"refFill": "#303C42"
		}
	}
}
