//!!! Generated by svg2meta.mjs
// From src\hmi\industry\pipe11.svg 
export const  Pipe11Meta = {
	"root": {
		"fill": "#000000",
		"height": "800px",
		"width": "800px",
		"version": "1.1",
		"id": "Layer_1",
		"xmlns": "http://www.w3.org/2000/svg",
		"xmlns:xlink": "http://www.w3.org/1999/xlink",
		"viewBox": "0 0 512 512",
		"xml:space": "preserve"
	},
	"markup": [],
	"attrs": {}
}
