//!!! Generated by svg2meta.mjs
// From src\hmi\geometry\arrow-right-block.svg 
export const  ArrowRightBlockMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M256 512l512 409.6V102.4L256 512z",
			"fill": "#333333"
		}
	}
}
