// !!! Generated by svg2ts.mjs
// From src\hmi\geometry\arrow-right.svg 
export const  ArrowRightSvg = `<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1686711383012" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="10488" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200"><path d="M343.552 66.048L270.848 138.752l373.76 373.248-373.76 373.248 72.704 72.704 445.44-445.952-445.44-445.952z" fill="#333333" p-id="10489"></path></svg>`
