//!!! Generated by svg2meta.mjs
// From src\hmi\geometry\arrow-left.svg 
export const  ArrowLeftMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M753.152 138.752l-72.704-72.704L235.008 512l445.44 445.952 72.704-72.704L379.392 512l373.76-373.248z",
			"fill": "#333333"
		}
	}
}
