//!!! Generated by svg2meta.mjs
// From src\hmi\geometry\arrow-right.svg 
export const  ArrowRightMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M343.552 66.048L270.848 138.752l373.76 373.248-373.76 373.248 72.704 72.704 445.44-445.952-445.44-445.952z",
			"fill": "#333333"
		}
	}
}
