//!!! Generated by svg2meta.mjs
// From src\hmi\geometry\arrow-left-block.svg 
export const  ArrowLeftBlockMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M256 102.4v819.2l512-409.6L256 102.4z"
		}
	}
}
