//!!! Generated by svg2meta.mjs
// From src\hmi\geometry\left.svg 
export const  LeftMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M1024 460.8H196.096l219.648-219.648-72.192-72.704L0 512l343.552 343.552 72.192-72.704L196.096 563.2H1024V460.8z"
		}
	}
}
