//!!! Generated by svg2meta.mjs
// From src\hmi\geometry\pentagon.svg 
export const  PentagonMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M512 210.176l320.512 232.832L710.059 819.84H313.94L191.488 443.008 512 210.176z m405.76 205.141L512 120.491 106.24 415.317l154.965 477.014h501.59l155.008-477.014z"
		}
	}
}
