//!!! Generated by svg2meta.mjs
// From src\hmi\geometry\right.svg 
export const  RightMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M680.448 168.448l-72.192 72.704L827.904 460.8H0v102.4h827.904l-219.648 219.648 72.192 72.704L1024 512l-343.552-343.552z",
			"fill": "#333333"
		}
	}
}
