const fs = require("fs")
const path = require("path")

const dir = __dirname
const out = "svg.ts"

const prefix = ""

let files = fs.readdirSync(dir)

fs.writeFileSync(out, "//!!! generated by svg2ts.js\n\n")

files.forEach(file => {
    const filename = path.join(dir, file)
    const stat = fs.statSync(filename)
    const ext = path.extname(file)
    if (stat.isFile() && ext === ".svg") {
        fs.appendFileSync(out, "//" + filename + "\n")

        const param = path.basename(file, ext)
        fs.appendFileSync(out, "export const " + prefix + param + "_svg =`")

        const content = fs.readFileSync(filename)
        fs.appendFileSync(out, content)
        fs.appendFileSync(out, "`\n\n")
    }

})
