//!!! Generated by svg2meta.mjs
// From src\hmi\electric\capacitor.svg 
export const  CapacitorMeta = {
	"root": {
		"fill": "#000000",
		"height": "800px",
		"width": "800px",
		"version": "1.1",
		"id": "Capa_1",
		"xmlns": "http://www.w3.org/2000/svg",
		"xmlns:xlink": "http://www.w3.org/1999/xlink",
		"viewBox": "0 0 460 460",
		"xml:space": "preserve"
	},
	"markup": [],
	"attrs": {}
}
