//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric15.svg 
export const  Electric15Meta = {
	"root": {
		"fill": "#000000",
		"width": "800px",
		"height": "800px",
		"viewBox": "-1.41 0 16 16",
		"xmlns": "http://www.w3.org/2000/svg"
	},
	"markup": [],
	"attrs": {}
}
