//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric13.svg 
export const  Electric13Meta = {
	"width": 800,
	"height": 800,
	"viewBox": "0 0 64 64",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"fill": "#000",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path2",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path3",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path4",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path5",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path6",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path7",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path8",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path9",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path10",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path11",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path12",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path13",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path14",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path15",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path16",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path17",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path18",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path19",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path20",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path21",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path22",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path23",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path24",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path25",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path26",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path27",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path28",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path29",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path30",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path31",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path32",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M56,10h4c1.1,0,2,0.9,2,2v20l0,0h-8l0,0V12C54,10.9,54.9,10,56,10z"
		},
		"path2": {
			"refD": "M59,7h-2V4H47v3h-2V3c0-0.6,0.4-1,1-1h12c0.6,0,1,0.4,1,1V7z"
		},
		"path3": {
			"refD": "M44,10V8c0-1.1,0.9-2,2-2l0,0c1.1,0,2,0.9,2,2v2"
		},
		"path4": {
			"refD": "M56,10V8c0-1.1,0.9-2,2-2l0,0c1.1,0,2,0.9,2,2v2"
		},
		"path5": {
			"refD": "M20,22h32c5.5,0,10,4.5,10,10v10c0,5.5-4.5,10-10,10H20c-5.5,0-10-4.5-10-10V32C10,26.5,14.5,22,20,22z"
		},
		"path6": {
			"refD": "M44,10h4c1.1,0,2,0.9,2,2v10l0,0h-8l0,0V12C42,10.9,42.9,10,44,10z"
		},
		"path7": {
			"refD": "M59,38h-2v-6c0-2.8-2.2-5-5-5v-2c3.9,0,7,3.1,7,7V38z"
		},
		"path8": {
			"refD": "M10 32L6 32 6 42 10 42"
		},
		"path9": {
			"refD": "M2 32h4v30h-4z"
		},
		"path10": {
			"refD": "M2 57h4v2h-4z"
		},
		"path11": {
			"refD": "M34 2h4v20h-4z"
		},
		"path12": {
			"refD": "M34 2h4v4h-4z"
		},
		"path13": {
			"refD": "M2 2h4v20h-4z"
		},
		"path14": {
			"refD": "M2 2h4v4h-4z"
		},
		"path15": {
			"refD": "M6 4h28v2h-28z"
		},
		"path16": {
			"refD": "M6 9h28v2h-28z"
		},
		"path17": {
			"refD": "M6 14h28v2h-28z"
		},
		"path18": {
			"refD": "M6 19h28v2h-28z"
		},
		"path19": {
			"refD": "M33 22h2v30h-2z"
		},
		"path20": {
			"refD": "M25 22h2v30h-2z"
		},
		"path21": {
			"refD": "M26 31h8v2h-8z"
		},
		"path22": {
			"refD": "M26 27h8v2h-8z"
		},
		"path23": {
			"refD": "M26 35h8v2h-8z"
		},
		"path24": {
			"refD": "M26 39h8v2h-8z"
		},
		"path25": {
			"refD": "M26 43h8v2h-8z"
		},
		"path26": {
			"refD": "M26 47h8v2h-8z"
		},
		"path27": {
			"refD": "M19 52h4v6h-4z"
		},
		"path28": {
			"refD": "M49 52h4v6h-4z"
		},
		"path29": {
			"refD": "M42 13h8v2h-8z"
		},
		"path30": {
			"refD": "M54 13h8v2h-8z"
		},
		"path31": {
			"refD": "M2 35h4v2h-4z"
		},
		"path32": {
			"refD": "M15 58h42v4h-42z"
		}
	},
	"path": "M56,10h4c1.1,0,2,0.9,2,2v20l0,0h-8l0,0V12C54,10.9,54.9,10,56,10z,M59,7h-2V4H47v3h-2V3c0-0.6,0.4-1,1-1h12c0.6,0,1,0.4,1,1V7z,M44,10V8c0-1.1,0.9-2,2-2l0,0c1.1,0,2,0.9,2,2v2,M56,10V8c0-1.1,0.9-2,2-2l0,0c1.1,0,2,0.9,2,2v2,M20,22h32c5.5,0,10,4.5,10,10v10c0,5.5-4.5,10-10,10H20c-5.5,0-10-4.5-10-10V32C10,26.5,14.5,22,20,22z,M44,10h4c1.1,0,2,0.9,2,2v10l0,0h-8l0,0V12C42,10.9,42.9,10,44,10z,M59,38h-2v-6c0-2.8-2.2-5-5-5v-2c3.9,0,7,3.1,7,7V38z,M10 32L6 32 6 42 10 42,M2 32h4v30h-4z,M2 57h4v2h-4z,M34 2h4v20h-4z,M34 2h4v4h-4z,M2 2h4v20h-4z,M2 2h4v4h-4z,M6 4h28v2h-28z,M6 9h28v2h-28z,M6 14h28v2h-28z,M6 19h28v2h-28z,M33 22h2v30h-2z,M25 22h2v30h-2z,M26 31h8v2h-8z,M26 27h8v2h-8z,M26 35h8v2h-8z,M26 39h8v2h-8z,M26 43h8v2h-8z,M26 47h8v2h-8z,M19 52h4v6h-4z,M49 52h4v6h-4z,M42 13h8v2h-8z,M54 13h8v2h-8z,M2 35h4v2h-4z,M15 58h42v4h-42z,"
}
