//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric18.svg 
export const  Electric18Meta = {
	"width": 800,
	"height": 800,
	"viewBox": "0 0 24 24",
	"xmlns": "http://www.w3.org/2000/svg",
	"fill": "none",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "group1"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M15.59 5H15.25V2C15.25 1.59 14.91 1.25 14.5 1.25C14.09 1.25 13.75 1.59 13.75 2V5H10.25V2C10.25 1.59 9.91 1.25 9.5 1.25C9.09 1.25 8.75 1.59 8.75 2V5H8.41C7.36 5 6.5 5.86 6.5 6.91V12C6.5 14.2 8 16 10.5 16H11.25V22C11.25 22.41 11.59 22.75 12 22.75C12.41 22.75 12.75 22.41 12.75 22V16H13.5C16 16 17.5 14.2 17.5 12V6.91C17.5 5.86 16.64 5 15.59 5Z",
			"refFill": "#292D32"
		}
	}
}
