//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric12.svg 
export const  Electric12Meta = {
	"root": {
		"width": "800px",
		"height": "800px",
		"viewBox": "0 0 32 32",
		"id": "svg5",
		"version": "1.1",
		"xmlns": "http://www.w3.org/2000/svg",
		"xmlns:svg": "http://www.w3.org/2000/svg"
	},
	"markup": [],
	"attrs": {}
}
