//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric12.svg 
export const  Electric12Meta = {
	"width": 800,
	"height": 800,
	"viewBox": "0 0 32 32",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "group1"
		},
		{
			"tagName": "path",
			"selector": "path2",
			"groupSelector": "group1"
		},
		{
			"tagName": "path",
			"selector": "path3",
			"groupSelector": "group1"
		}
	],
	"attrs": {
		"path1": {
			"refD": "m 167,105 c -1.6447,0 -3,1.3553 -3,3 v 19 c 0,1.6447 1.3553,3 3,3 h 10 c 1.6447,0 3,-1.3553 3,-3 v -19 c 0,-1.6447 -1.3553,-3 -3,-3 z m 0,2 h 10 c 0.5713,0 1,0.4287 1,1 v 19 c 0,0.5713 -0.4287,1 -1,1 h -10 c -0.5713,0 -1,-0.4287 -1,-1 v -19 c 0,-0.5713 0.4287,-1 1,-1 z"
		},
		"path2": {
			"refD": "m 172.31641,110.55078 a 1,1 0 0 0 -1.26563,0.63281 l -2,6 A 1.0001,1.0001 0 0 0 170,118.5 h 2.61133 l -1.56055,4.68359 a 1,1 0 0 0 0.63281,1.26563 1,1 0 0 0 1.26563,-0.63281 l 2,-6 A 1.0001,1.0001 0 0 0 174,116.5 h -2.61133 l 1.56055,-4.68359 a 1,1 0 0 0 -0.63281,-1.26563 z"
		},
		"path3": {
			"refD": "m 169,102 c -1.0907,0 -2,0.9093 -2,2 v 1 c 0,1.0907 0.9093,2 2,2 h 6 c 1.0907,0 2,-0.9093 2,-2 v -1 c 0,-1.0907 -0.9093,-2 -2,-2 z m 0,2 h 6 v 1 h -6 z"
		}
	}
}
