//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric17.svg 
export const  Electric17Meta = {
	"width": 800,
	"height": 800,
	"viewBox": "0 0 24 24",
	"xmlns": "http://www.w3.org/2000/svg",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path2",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path3",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path4",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path5",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path6",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path7",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path8",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M1.5 3.41a1.91 1.91 0 0 1 1.91 -1.91h17.18a1.91 1.91 0 0 1 1.91 1.91v17.18a1.91 1.91 0 0 1 -1.91 1.91h-17.18a1.91 1.91 0 0 1 -1.91 -1.91z"
		},
		"path2": {
			"refD": "M5.32 12a6.68 6.68 0 1 0 13.36 0a6.68 6.68 0 1 0 -13.36 0z"
		},
		"path3": {
			"refD": "M3.41 4.36a0.95 0.95 0 1 0 1.9 0a0.95 0.95 0 1 0 -1.9 0z"
		},
		"path4": {
			"refD": "M18.69 4.36a0.95 0.95 0 1 0 1.9 0a0.95 0.95 0 1 0 -1.9 0z"
		},
		"path5": {
			"refD": "M18.69 19.64a0.95 0.95 0 1 0 1.9 0a0.95 0.95 0 1 0 -1.9 0z"
		},
		"path6": {
			"refD": "M3.41 19.64a0.95 0.95 0 1 0 1.9 0a0.95 0.95 0 1 0 -1.9 0z"
		},
		"path7": {
			"refD": "M9.14 10.09L9.14 13.91"
		},
		"path8": {
			"refD": "M14.86 10.09L14.86 13.91"
		}
	},
	"path": "M1.5 3.41a1.91 1.91 0 0 1 1.91 -1.91h17.18a1.91 1.91 0 0 1 1.91 1.91v17.18a1.91 1.91 0 0 1 -1.91 1.91h-17.18a1.91 1.91 0 0 1 -1.91 -1.91z,M5.32 12a6.68 6.68 0 1 0 13.36 0a6.68 6.68 0 1 0 -13.36 0z,M3.41 4.36a0.95 0.95 0 1 0 1.9 0a0.95 0.95 0 1 0 -1.9 0z,M18.69 4.36a0.95 0.95 0 1 0 1.9 0a0.95 0.95 0 1 0 -1.9 0z,M18.69 19.64a0.95 0.95 0 1 0 1.9 0a0.95 0.95 0 1 0 -1.9 0z,M3.41 19.64a0.95 0.95 0 1 0 1.9 0a0.95 0.95 0 1 0 -1.9 0z,M9.14 10.09L9.14 13.91,M14.86 10.09L14.86 13.91,"
}
