// !!! Generated by svg2ts.mjs
// From src\hmi\electric\electric4.svg 
export const  Electric4Svg = `<?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
<svg width="800px" height="800px" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" version="1.1" fill="none"  stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5">
<path d="m8 1.75v6.5m4.25-5s2 1.29822 2 4.75-2.79822 6.25-6.25 6.25-6.25-2.79822-6.25-6.25 2-4.75 2-4.75"/>
</svg>`
