//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric1.svg 
export const  Electric1Meta = {
	"root": {
		"viewBox": "0 0 24 24",
		"fill": "none",
		"xmlns": "http://www.w3.org/2000/svg"
	},
	"markup": [
		{
			"tagName": "path",
			"selector": "path0"
		},
		{
			"tagName": "path",
			"selector": "path1"
		},
		{
			"tagName": "path",
			"selector": "path2"
		},
		{
			"tagName": "path",
			"selector": "path3"
		}
	],
	"attrs": {
		"path0": {
			"refD": "M10.5 16H13.5C16 16 17.5 14.2 17.5 12V6.91C17.5 5.86 16.64 5 15.59 5H8.42006C7.37006 5 6.51006 5.86 6.51006 6.91V12C6.50006 14.2 8.00005 16 10.5 16Z",
			"refStroke": "#292D32",
			"refStrokeWidth": 1.5,
			"refStrokeLinecap": "round",
			"refStrokeLinejoin": "round"
		},
		"path1": {
			"refD": "M9.5 2V5",
			"refStroke": "#292D32",
			"refStrokeWidth": 1.5,
			"refStrokeLinecap": "round",
			"refStrokeLinejoin": "round"
		},
		"path2": {
			"refD": "M14.5 2V5",
			"refStroke": "#292D32",
			"refStrokeWidth": 1.5,
			"refStrokeLinecap": "round",
			"refStrokeLinejoin": "round"
		},
		"path3": {
			"refD": "M12 22V16",
			"refStroke": "#292D32",
			"refStrokeWidth": 1.5,
			"refStrokeLinecap": "round",
			"refStrokeLinejoin": "round"
		}
	}
}
