//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric4.svg 
export const  Electric4Meta = {
	"width": 800,
	"height": 800,
	"viewBox": "0 0 16 16",
	"markup": [
		{
			"tagName": "path",
			"selector": "path0"
		}
	],
	"attrs": {
		"path0": {
			"refD": "m8 1.75v6.5m4.25-5s2 1.29822 2 4.75-2.79822 6.25-6.25 6.25-6.25-2.79822-6.25-6.25 2-4.75 2-4.75"
		}
	}
}
