//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric6.svg 
export const  Electric6Meta = {
	"root": {
		"t": "1685345396925",
		"class": "icon",
		"viewBox": "0 0 1024 1024",
		"version": "1.1",
		"xmlns": "http://www.w3.org/2000/svg",
		"p-id": "4944",
		"xmlns:xlink": "http://www.w3.org/1999/xlink",
		"width": "200",
		"height": "200"
	},
	"markup": [
		{
			"tagName": "path",
			"selector": "path0"
		},
		{
			"tagName": "path",
			"selector": "path1"
		},
		{
			"tagName": "path",
			"selector": "path2"
		}
	],
	"attrs": {
		"path0": {
			"refD": "M512 64.887129a447.234535 447.234535 0 0 1 174.00903 859.085307A447.228451 447.228451 0 0 1 337.990971 99.997149 444.172673 444.172673 0 0 1 512 64.887129m0-64.887129c-282.765941 0-512 229.223921-512 512s229.223921 512 512 512 512-229.223921 512-512-229.234059-512-512-512z",
			"refFill": "#333333"
		},
		"path1": {
			"refD": "M272.876737 320.32545l45.882297-45.882298 430.61836 430.617347-45.882297 45.883311z",
			"refFill": "#333333"
		},
		"path2": {
			"refD": "M273.583398 704.854685l430.617347-430.617346 45.883311 45.881283-430.618361 430.61836z",
			"refFill": "#333333"
		}
	}
}
