// !!! Generated by svg2ts.mjs
// From .\src\hmi\electric\electric7.svg 
export const  Electric7Svg = `<svg fill="#000000" height="200px" width="200px" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 298 298"
    xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 298 298">
    <path d="M298,141h-50v-41H50v41H0v16h50v41h198v-41h50V141z M66,182v-66h166v66H66z"></path>
</svg>`
