//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric7.svg 
export const  Electric7Meta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 298 298",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"fill": "#000000",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M298,141h-50v-41H50v41H0v16h50v41h198v-41h50V141z M66,182v-66h166v66H66z"
		}
	}
}
