//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric17.svg 
export const  Electric17Meta = {
	"width": 800,
	"height": 800,
	"viewBox": "0 0 24 24",
	"xmlns": "http://www.w3.org/2000/svg",
	"markup": [
		{
			"tagName": "rect",
			"selector": "rect1"
		},
		{
			"tagName": "circle",
			"selector": "circle2"
		},
		{
			"tagName": "circle",
			"selector": "circle3"
		},
		{
			"tagName": "circle",
			"selector": "circle4"
		},
		{
			"tagName": "circle",
			"selector": "circle5"
		},
		{
			"tagName": "circle",
			"selector": "circle6"
		},
		{
			"tagName": "line",
			"selector": "line7"
		},
		{
			"tagName": "line",
			"selector": "line8"
		}
	],
	"attrs": {
		"rect1": {
			"refX": 1.5,
			"refY": 1.5,
			"refWidth": 21,
			"refHeight": 21,
			"refRx": 1.91
		},
		"circle2": {
			"refCx": 12,
			"refCy": 12,
			"refR": 6.68
		},
		"circle3": {
			"refCx": 4.36,
			"refCy": 4.36,
			"refR": 0.95
		},
		"circle4": {
			"refCx": 19.64,
			"refCy": 4.36,
			"refR": 0.95
		},
		"circle5": {
			"refCx": 19.64,
			"refCy": 19.64,
			"refR": 0.95
		},
		"circle6": {
			"refCx": 4.36,
			"refCy": 19.64,
			"refR": 0.95
		},
		"line7": {
			"refX1": 9.14,
			"refY1": 10.09,
			"refX2": 9.14,
			"refY2": 13.91
		},
		"line8": {
			"refX1": 14.86,
			"refY1": 10.09,
			"refX2": 14.86,
			"refY2": 13.91
		}
	}
}
