//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric13.svg 
export const  Electric13Meta = {
	"root": {
		"width": "800px",
		"height": "800px",
		"viewBox": "0 0 64 64",
		"id": "Layer_1",
		"version": "1.1",
		"xml:space": "preserve",
		"xmlns": "http://www.w3.org/2000/svg",
		"xmlns:xlink": "http://www.w3.org/1999/xlink"
	},
	"markup": [],
	"attrs": {}
}
