//!!! Generated by svg2meta.mjs
// From src\hmi\electric\electric11.svg 
export const  Electric11Meta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 231 231",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"fill": "#000000",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M182.326,0H48.674l58.492,92.89V231h16V92.887L182.326,0z M153.253,16l-37.755,59.616L77.745,16H153.253z"
		}
	},
	"path": "M182.326,0H48.674l58.492,92.89V231h16V92.887L182.326,0z M153.253,16l-37.755,59.616L77.745,16H153.253z,"
}
