// !!! Generated by svg2ts.mjs
// From .\src\hmi\electric\electric11.svg 
export const  Electric11Svg = `<svg fill="#000000" height="200px" width="200px" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 231 231"
    xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 231 231">
    <path d="M182.326,0H48.674l58.492,92.89V231h16V92.887L182.326,0z M153.253,16l-37.755,59.616L77.745,16H153.253z">
    </path>
</svg>`
