// !!! Generated by svg2ts.mjs
// From src\hmi\electric\switch.svg 
export const  SwitchSvg = `<?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
<svg width="800px" height="800px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><rect width="24" height="24" fill="none"/><path d="M23,14v2H17V14ZM14,8.93h0L12.59,7.51h0l-.7-.7L4.81,13.88l-.1.12H1v2H7v-.07l7-7Z"/></svg>`
