//!!! Generated by svg2meta.mjs
// From src\hmi\electric\switch.svg 
export const  SwitchMeta = {
	"width": 800,
	"height": 800,
	"viewBox": "0 0 24 24",
	"markup": [
		{
			"tagName": "rect",
			"selector": "rect0"
		},
		{
			"tagName": "path",
			"selector": "path0"
		}
	],
	"attrs": {
		"rect0": {
			"refWidth": 24,
			"refHeight": 24,
			"refFill": "none"
		},
		"path0": {
			"refD": "M23,14v2H17V14ZM14,8.93h0L12.59,7.51h0l-.7-.7L4.81,13.88l-.1.12H1v2H7v-.07l7-7Z"
		}
	}
}
