// !!! Generated by svg2ts.mjs
// From .\src\hmi\electric\switch.svg 
export const  SwitchSvg = `<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Uploaded to: SVG Repo, www.svgrepo.com, Transformed by: SVG Repo Mixer Tools -->
<svg fill="#000000" height="800px" width="800px" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 298 298" xmlns:xlink="http://www.w3.org/1999/xlink" enable-background="new 0 0 298 298">
<g id="SVGRepo_bgCarrier" stroke-width="0"/>
<g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"/>
<g id="SVGRepo_iconCarrier"> <g> <path d="m298,178.248h-59.517c-3.323-9.592-12.442-16.5-23.151-16.5-13.51,0-24.5,10.99-24.5,24.5 0,13.51 10.99,24.5 24.5,24.5 10.709,0 19.828-6.908 23.151-16.5h59.517v-16zm-74.168,8c0,4.687-3.814,8.5-8.5,8.5-4.687,0-8.5-3.813-8.5-8.5 0-4.686 3.813-8.5 8.5-8.5 4.686,0 8.5,3.813 8.5,8.5z"/> <path d="m171.014,87.252l-76.967,76.967c-3.238-1.582-6.873-2.472-10.713-2.472-10.709,0-19.828,6.908-23.151,16.5h-60.183v16h60.183c3.323,9.592 12.442,16.5 23.151,16.5 13.51,0 24.5-10.99 24.5-24.5 0-3.841-0.891-7.476-2.472-10.715l76.966-76.966-11.314-11.314zm-96.18,98.996c0-4.686 3.813-8.5 8.5-8.5s8.5,3.814 8.5,8.5c0,4.687-3.813,8.5-8.5,8.5s-8.5-3.814-8.5-8.5z"/> </g> </g>
</svg>`
