basePath: /app/scada/api/
definitions:
  api.Device:
    properties:
      area_id:
        description: 区域
        type: string
      created:
        type: string
      desc:
        type: string
      disabled:
        type: boolean
      gateway_id:
        type: string
      group_id:
        description: 分组
        type: string
      id:
        description: ClientID
        type: string
      name:
        type: string
      parameters:
        additionalProperties:
          type: number
        description: 模型参数，用于报警检查
        type: object
      product_id:
        type: string
      type_id:
        description: 类型
        type: string
    type: object
  api.ParamSearch:
    properties:
      filter:
        additionalProperties: true
        type: object
      keyword:
        additionalProperties:
          type: string
        type: object
      limit:
        type: integer
      skip:
        type: integer
      sort:
        additionalProperties:
          type: integer
        type: object
    type: object
  api.ReplyData-api_Device:
    properties:
      data:
        $ref: '#/definitions/api.Device'
      error:
        type: string
    type: object
  api.ReplyData-int64:
    properties:
      data:
        type: integer
      error:
        type: string
    type: object
  api.ReplyData-types_DeviceArea:
    properties:
      data:
        $ref: '#/definitions/types.DeviceArea'
      error:
        type: string
    type: object
  api.ReplyData-types_DeviceGroup:
    properties:
      data:
        $ref: '#/definitions/types.DeviceGroup'
      error:
        type: string
    type: object
  api.ReplyData-types_DeviceType:
    properties:
      data:
        $ref: '#/definitions/types.DeviceType'
      error:
        type: string
    type: object
  api.ReplyList-api_Device:
    properties:
      data:
        items:
          $ref: '#/definitions/api.Device'
        type: array
      error:
        type: string
      total:
        type: integer
    type: object
  api.ReplyList-types_DeviceArea:
    properties:
      data:
        items:
          $ref: '#/definitions/types.DeviceArea'
        type: array
      error:
        type: string
      total:
        type: integer
    type: object
  api.ReplyList-types_DeviceGroup:
    properties:
      data:
        items:
          $ref: '#/definitions/types.DeviceGroup'
        type: array
      error:
        type: string
      total:
        type: integer
    type: object
  api.ReplyList-types_DeviceType:
    properties:
      data:
        items:
          $ref: '#/definitions/types.DeviceType'
        type: array
      error:
        type: string
      total:
        type: integer
    type: object
  types.DeviceArea:
    properties:
      created:
        type: string
      desc:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  types.DeviceGroup:
    properties:
      area_id:
        type: string
      created:
        type: string
      desc:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  types.DeviceType:
    properties:
      created:
        type: string
      desc:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  description: API文档
  title: 设备分类数据接口文档
  version: 1.0 版本
paths:
  /project/{id}:
    get:
      consumes:
      - application/json
      description: 获取工程
      parameters:
      - description: 工程ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-api_Device'
      summary: 获取工程
      tags:
      - project
    post:
      consumes:
      - application/json
      description: 修改工程
      parameters:
      - description: 工程ID
        in: path
        name: id
        required: true
        type: integer
      - description: 工程信息
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/api.Device'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-api_Device'
      summary: 修改工程
      tags:
      - project
  /project/area/{id}:
    get:
      consumes:
      - application/json
      description: 获取区域
      parameters:
      - description: 区域ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceArea'
      summary: 获取区域
      tags:
      - project-area
    post:
      consumes:
      - application/json
      description: 修改区域
      parameters:
      - description: 区域ID
        in: path
        name: id
        required: true
        type: string
      - description: 区域信息
        in: body
        name: project-area
        required: true
        schema:
          $ref: '#/definitions/types.DeviceArea'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceArea'
      summary: 修改区域
      tags:
      - project-area
  /project/area/{id}/delete:
    get:
      consumes:
      - application/json
      description: 删除区域
      parameters:
      - description: 区域ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceArea'
      summary: 删除区域
      tags:
      - project-area
  /project/area/count:
    post:
      consumes:
      - application/json
      description: 查询区域数量
      parameters:
      - description: 查询参数
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/api.ParamSearch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-int64'
      summary: 查询区域数量
      tags:
      - project-area
  /project/area/create:
    post:
      consumes:
      - application/json
      description: 创建区域
      parameters:
      - description: 区域信息
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/types.DeviceArea'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceArea'
      summary: 创建区域
      tags:
      - project-area
  /project/area/export:
    get:
      consumes:
      - application/json
      description: 导出区域
      produces:
      - application/octet-stream
      responses: {}
      summary: 导出区域
      tags:
      - project-area
  /project/area/import:
    post:
      consumes:
      - multipart/form-data
      description: 导入区域
      parameters:
      - description: 压缩包
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-int64'
      summary: 导入区域
      tags:
      - project-area
  /project/area/list:
    get:
      consumes:
      - application/json
      description: 查询区域
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: skip
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyList-types_DeviceArea'
      summary: 查询区域
      tags:
      - project-area
  /project/area/search:
    post:
      consumes:
      - application/json
      description: 查询区域
      parameters:
      - description: 查询参数
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/api.ParamSearch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyList-types_DeviceArea'
      summary: 查询区域
      tags:
      - project-area
  /project/group/{id}:
    get:
      consumes:
      - application/json
      description: 获取分组
      parameters:
      - description: 分组ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceGroup'
      summary: 获取分组
      tags:
      - project-group
    post:
      consumes:
      - application/json
      description: 修改分组
      parameters:
      - description: 分组ID
        in: path
        name: id
        required: true
        type: string
      - description: 分组信息
        in: body
        name: project-group
        required: true
        schema:
          $ref: '#/definitions/types.DeviceGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceGroup'
      summary: 修改分组
      tags:
      - project-group
  /project/group/{id}/delete:
    get:
      consumes:
      - application/json
      description: 删除分组
      parameters:
      - description: 分组ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceGroup'
      summary: 删除分组
      tags:
      - project-group
  /project/group/count:
    post:
      consumes:
      - application/json
      description: 查询分组数量
      parameters:
      - description: 查询参数
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/api.ParamSearch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-int64'
      summary: 查询分组数量
      tags:
      - project-group
  /project/group/create:
    post:
      consumes:
      - application/json
      description: 创建分组
      parameters:
      - description: 分组信息
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/types.DeviceGroup'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceGroup'
      summary: 创建分组
      tags:
      - project-group
  /project/group/export:
    get:
      consumes:
      - application/json
      description: 导出分组
      produces:
      - application/octet-stream
      responses: {}
      summary: 导出分组
      tags:
      - project-group
  /project/group/import:
    post:
      consumes:
      - multipart/form-data
      description: 导入分组
      parameters:
      - description: 压缩包
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-int64'
      summary: 导入分组
      tags:
      - project-group
  /project/group/list:
    get:
      consumes:
      - application/json
      description: 查询分组
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: skip
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyList-types_DeviceGroup'
      summary: 查询分组
      tags:
      - project-group
  /project/group/search:
    post:
      consumes:
      - application/json
      description: 查询分组
      parameters:
      - description: 查询参数
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/api.ParamSearch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyList-types_DeviceGroup'
      summary: 查询分组
      tags:
      - project-group
  /project/list:
    get:
      consumes:
      - application/json
      description: 查询工程
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: skip
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyList-api_Device'
      summary: 查询工程
      tags:
      - project
  /project/search:
    post:
      consumes:
      - application/json
      description: 查询工程
      parameters:
      - description: 查询参数
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/api.ParamSearch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyList-api_Device'
      summary: 查询工程
      tags:
      - project
  /project/type/{id}:
    get:
      consumes:
      - application/json
      description: 获取设备类型
      parameters:
      - description: 设备类型ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceType'
      summary: 获取设备类型
      tags:
      - project-type
    post:
      consumes:
      - application/json
      description: 修改设备类型
      parameters:
      - description: 设备类型ID
        in: path
        name: id
        required: true
        type: string
      - description: 设备类型信息
        in: body
        name: project-type
        required: true
        schema:
          $ref: '#/definitions/types.DeviceType'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceType'
      summary: 修改设备类型
      tags:
      - project-type
  /project/type/{id}/delete:
    get:
      consumes:
      - application/json
      description: 删除设备类型
      parameters:
      - description: 设备类型ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceType'
      summary: 删除设备类型
      tags:
      - project-type
  /project/type/count:
    post:
      consumes:
      - application/json
      description: 查询设备类型数量
      parameters:
      - description: 查询参数
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/api.ParamSearch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-int64'
      summary: 查询设备类型数量
      tags:
      - project-type
  /project/type/create:
    post:
      consumes:
      - application/json
      description: 创建设备类型
      parameters:
      - description: 设备类型信息
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/types.DeviceType'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-types_DeviceType'
      summary: 创建设备类型
      tags:
      - project-type
  /project/type/export:
    get:
      consumes:
      - application/json
      description: 导出设备类型
      produces:
      - application/octet-stream
      responses: {}
      summary: 导出设备类型
      tags:
      - project-type
  /project/type/import:
    post:
      consumes:
      - multipart/form-data
      description: 导入设备类型
      parameters:
      - description: 压缩包
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyData-int64'
      summary: 导入设备类型
      tags:
      - project-type
  /project/type/list:
    get:
      consumes:
      - application/json
      description: 查询设备类型
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: skip
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyList-types_DeviceType'
      summary: 查询设备类型
      tags:
      - project-type
  /project/type/search:
    post:
      consumes:
      - application/json
      description: 查询设备类型
      parameters:
      - description: 查询参数
        in: body
        name: search
        required: true
        schema:
          $ref: '#/definitions/api.ParamSearch'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.ReplyList-types_DeviceType'
      summary: 查询设备类型
      tags:
      - project-type
swagger: "2.0"
