//!!! Generated by svg2meta.mjs
// From src\hmi\base\image.svg 
export const  ImageMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path2",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path3",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M896 626.592a16 16 0 0 0-7.68-13.664l-172.448-105.088a16 16 0 0 0-20.704 3.52l-76 92.608-1.024 1.152a16 16 0 0 1-22.624 0.032l-252.832-252.064a16.032 16.032 0 0 0-22.08-0.512l-187.36 170.656a15.936 15.936 0 0 0-5.248 11.84V800h768v-173.408z"
		},
		"path2": {
			"refD": "M800 320m-64 0a64 64 0 1 0 128 0 64 64 0 1 0-128 0Z"
		},
		"path3": {
			"refD": "M32 128v768h960V128H32z m896 704H96V192h832v640z"
		}
	}
}
