//!!! Generated by svg2meta.mjs
// From src\hmi\base\input.svg 
export const  InputMeta = {
	"root": {
		"t": "1681075864490",
		"class": "icon",
		"viewBox": "0 0 1024 1024",
		"version": "1.1",
		"xmlns": "http://www.w3.org/2000/svg",
		"p-id": "23339",
		"xmlns:xlink": "http://www.w3.org/1999/xlink",
		"width": "200",
		"height": "200"
	},
	"markup": [
		{
			"tagName": "path",
			"selector": "path0"
		},
		{
			"tagName": "path",
			"selector": "path1"
		}
	],
	"attrs": {
		"path0": {
			"refD": "M896 224H128c-35.2 0-64 28.8-64 64v448c0 35.2 28.8 64 64 64h768c35.2 0 64-28.8 64-64V288c0-35.2-28.8-64-64-64z m0 480c0 19.2-12.8 32-32 32H160c-19.2 0-32-12.8-32-32V320c0-19.2 12.8-32 32-32h704c19.2 0 32 12.8 32 32v384z",
			"refFill": "#333333"
		},
		"path1": {
			"refD": "M224 352c-19.2 0-32 12.8-32 32v256c0 16 12.8 32 32 32s32-12.8 32-32V384c0-16-12.8-32-32-32z",
			"refFill": "#333333"
		}
	}
}
