//!!! Generated by svg2meta.mjs
// From src\hmi\base\line.svg 
export const  LineMeta = {
	"root": {
		"t": "1681075083419",
		"class": "icon",
		"viewBox": "0 0 1024 1024",
		"version": "1.1",
		"xmlns": "http://www.w3.org/2000/svg",
		"p-id": "5324",
		"xmlns:xlink": "http://www.w3.org/1999/xlink",
		"width": "200",
		"height": "200"
	},
	"markup": [
		{
			"tagName": "path",
			"selector": "path0"
		}
	],
	"attrs": {
		"path0": {
			"refD": "M191.488 864.768c-8.192 0-16.384-3.072-22.528-9.216-12.288-12.288-12.288-32.768 0-45.056L809.472 168.96c12.288-12.288 32.768-12.288 45.056 0s12.288 32.768 0 45.056L214.016 855.04c-6.144 6.144-14.336 9.728-22.528 9.728z",
			"refFill": "#2c2c2c"
		}
	}
}
