// !!! Generated by svg2ts.mjs
// From src\hmi\base\rect.svg 
export const  RectSvg = `<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg t="1681075032865" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="3626" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200"><path d="M898.8 199.6v624.8H125.2V199.6h773.6m59.5-59.5H65.7v743.8h892.5V140.1h0.1z" p-id="3627"></path></svg>`
