//!!! Generated by svg2meta.mjs
// From src\hmi\base\slider.svg 
export const  SliderMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M951.453 476.844H523.672a131.836 131.836 0 0 0-254.18 0H72.547v70.312h196.945a131.836 131.836 0 0 0 254.18 0h427.781z"
		}
	}
}
