//!!! Generated by svg2meta.mjs
// From src\hmi\base\slider.svg 
export const  SliderMeta = {
	"root": {
		"t": "1681137899230",
		"class": "icon",
		"viewBox": "0 0 1024 1024",
		"version": "1.1",
		"xmlns": "http://www.w3.org/2000/svg",
		"p-id": "28561",
		"xmlns:xlink": "http://www.w3.org/1999/xlink",
		"width": "200",
		"height": "200"
	},
	"markup": [
		{
			"tagName": "path",
			"selector": "path0"
		}
	],
	"attrs": {
		"path0": {
			"refD": "M951.453 476.844H523.672a131.836 131.836 0 0 0-254.18 0H72.547v70.312h196.945a131.836 131.836 0 0 0 254.18 0h427.781z"
		}
	}
}
