//!!! Generated by svg2meta.mjs
// From src\hmi\base\switch.svg 
export const  SwitchMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path2",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M751.36 768H272.64a271.36 271.36 0 0 1 0-542.72h478.72a271.36 271.36 0 0 1 0 542.72zM272.64 287.36a207.36 207.36 0 0 0 0 414.72h478.72a207.36 207.36 0 0 0 0-414.72z",
			"fill": "#323333"
		},
		"path2": {
			"refD": "M735.36 494.72m-158.08 0a158.08 158.08 0 1 0 316.16 0 158.08 158.08 0 1 0-316.16 0Z",
			"fill": "#323333"
		}
	}
}
