//!!! Generated by svg2meta.mjs
// From src\hmi\base\switch.svg 
export const  SwitchMeta = {
	"root": {
		"t": "1681137847659",
		"class": "icon",
		"viewBox": "0 0 1024 1024",
		"version": "1.1",
		"xmlns": "http://www.w3.org/2000/svg",
		"p-id": "25582",
		"xmlns:xlink": "http://www.w3.org/1999/xlink",
		"width": "200",
		"height": "200"
	},
	"markup": [
		{
			"tagName": "path",
			"selector": "path0"
		},
		{
			"tagName": "path",
			"selector": "path1"
		}
	],
	"attrs": {
		"path0": {
			"refD": "M751.36 768H272.64a271.36 271.36 0 0 1 0-542.72h478.72a271.36 271.36 0 0 1 0 542.72zM272.64 287.36a207.36 207.36 0 0 0 0 414.72h478.72a207.36 207.36 0 0 0 0-414.72z",
			"refFill": "#323333"
		},
		"path1": {
			"refD": "M735.36 494.72m-158.08 0a158.08 158.08 0 1 0 316.16 0 158.08 158.08 0 1 0-316.16 0Z",
			"refFill": "#323333"
		}
	}
}
