//!!! Generated by svg2meta.mjs
// From src\hmi\base\table.svg 
export const  TableMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M0 64l0 896 1024 0 0-896-1024 0zM384 640l0-192 256 0 0 192-256 0zM640 704l0 192-256 0 0-192 256 0zM640 192l0 192-256 0 0-192 256 0zM320 192l0 192-256 0 0-192 256 0zM64 448l256 0 0 192-256 0 0-192zM704 448l256 0 0 192-256 0 0-192zM704 384l0-192 256 0 0 192-256 0zM64 704l256 0 0 192-256 0 0-192zM704 896l0-192 256 0 0 192-256 0z",
			"fill": "#444444"
		}
	}
}
