//!!! Generated by svg2meta.mjs
// From src\hmi\base\time.svg 
export const  TimeMeta = {
	"width": 200,
	"height": 200,
	"viewBox": "0 0 1024 1024",
	"version": "1.1",
	"xmlns": "http://www.w3.org/2000/svg",
	"xmlns:xlink": "http://www.w3.org/1999/xlink",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		},
		{
			"tagName": "path",
			"selector": "path2",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M512 832c-176.448 0-320-143.552-320-320S335.552 192 512 192s320 143.552 320 320-143.552 320-320 320m0-704C300.256 128 128 300.256 128 512s172.256 384 384 384 384-172.256 384-384S723.744 128 512 128",
			"fill": "#3E3A39"
		},
		"path2": {
			"refD": "M544 505.856V320a32 32 0 0 0-64 0v199.104c0 8.48 3.36 16.64 9.376 22.624l107.296 107.296a31.904 31.904 0 0 0 45.248 0 32 32 0 0 0 0-45.248L544 505.856z",
			"fill": "#3E3A39"
		}
	}
}
