// !!! Generated by svg2ts.mjs
// From src\hmi\base\triangle.svg 
export const  TriangleSvg = `<?xml version="1.0" encoding="utf-8"?><!-- Uploaded to: SVG Repo, www.svgrepo.com, Generator: SVG Repo Mixer Tools -->
<svg width="800px" height="800px" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M20.5 18.5H4.5L12.5 5.5L20.5 18.5Z" stroke="#121923" stroke-width="1.2"/>
</svg>`
