//!!! Generated by svg2meta.mjs
// From src\hmi\base\triangle.svg 
export const  TriangleMeta = {
	"root": {
		"width": "800px",
		"height": "800px",
		"viewBox": "0 0 25 25",
		"fill": "none",
		"xmlns": "http://www.w3.org/2000/svg"
	},
	"markup": [
		{
			"tagName": "path",
			"selector": "path0"
		}
	],
	"attrs": {
		"path0": {
			"refD": "M20.5 18.5H4.5L12.5 5.5L20.5 18.5Z",
			"refStroke": "#121923",
			"refStrokeWidth": 1.2
		}
	}
}
