//!!! Generated by svg2meta.mjs
// From src\hmi\base\triangle.svg 
export const  TriangleMeta = {
	"width": 800,
	"height": 800,
	"viewBox": "0 0 25 25",
	"xmlns": "http://www.w3.org/2000/svg",
	"fill": "none",
	"markup": [
		{
			"tagName": "path",
			"selector": "path1",
			"groupSelector": "all"
		}
	],
	"attrs": {
		"path1": {
			"refD": "M20.5 18.5H4.5L12.5 5.5L20.5 18.5Z",
			"stroke": "#121923",
			"stroke-width": 1.2
		}
	}
}
